version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - npm install
      - npm build
      - ls -rlt build

artifacts:
  files:
    - '**/*'
  base-directory: 'out/**/*'
